const PLANES = [
  {
    id: 'esencial',
    nombre: 'ESENCIAL',
    precioMensual: 24.99,
    caracteristicas: [
      'Propiedades ilimitadas',
      'Página web auto-administrable',
      'Red inmobiliaria',
      'Certificado SSL en sitio web',
      'Correos electrónicos: 5',
      'Usuarios: 2',
      'Portales gratuitos',
      'Portales premium: 2',
    ],
  },
  {
    id: 'avanzado',
    nombre: 'AVANZADO',
    precioMensual: 44.99,
    caracteristicas: [
      'Propiedades ilimitadas',
      'Proyectos ilimitados',
      'Página web auto-administrable',
      'Red inmobiliaria',
      'Blog auto-administrable',
      'Certificado SSL en sitio web',
      'Correos electrónicos: 7',
      'Usuarios: 4',
      'Portales gratuitos',
      'Portales premium: Todos',
      'Redes Inmobiliarias Privadas',
      'Gestión de negocios',
      'Gestión de tasaciones y Análisis',
      'Comparativo de Mercado (ACM)',
      'Landing page de propiedades',
    ],
  },
  {
    id: 'profesional',
    nombre: 'PROFESIONAL',
    precioMensual: 72.99,
    caracteristicas: [
      'Propiedades ilimitadas',
      'Proyectos ilimitados',
      'Página web auto-administrable',
      'Red inmobiliaria',
      'Blog auto-administrable',
      'Certificado SSL en sitio web',
      'Correos electrónicos: 9',
      'Usuarios: 6',
      'Portales gratuitos',
      'Portales premium',
      'Redes Inmobiliarias Privadas',
      'Gestión de negocios',
      'Gestión de tasaciones y Análisis',
      'Comparativo de Mercado (ACM)',
      'Gestión de sucursales',
      'Landing page de propiedades',
      'Respuestas automáticas',
      'Integración de calendario',
      'Integración de email',
      'Gestión de sucursales',
    ],
  },
];

export function getPlans() {
  return PLANES;
}